import type {
  TriageStats,
  Repo,
  Issue,
  TriageEvent,
  Recommendation,
  SkillProfile,
  TriageConfig,
} from "./types";

// ─── Mock Triage Stats ─────────────────────────────────────────────────────

export const mockTriageStats: TriageStats = {
  totalTriaged: 52_847,
  aiAccuracy: 94.2,
  avgResponseTime: 2.4,
  activeContributors: 10_382,
  issueVolume: Array.from({ length: 30 }, (_, i) => ({
    date: new Date(
      Date.now() - (29 - i) * 24 * 60 * 60 * 1000
    ).toISOString().split("T")[0],
    count: Math.floor(Math.random() * 80) + 40,
  })),
  categoryBreakdown: [
    { category: "bug", count: 2340 },
    { category: "feature", count: 1890 },
    { category: "question", count: 980 },
    { category: "docs", count: 650 },
    { category: "chore", count: 430 },
    { category: "security", count: 180 },
    { category: "performance", count: 290 },
  ],
  priorityDistribution: [
    { priority: "P0", count: 120 },
    { priority: "P1", count: 580 },
    { priority: "P2", count: 1430 },
    { priority: "P3", count: 2100 },
  ],
  recentEvents: [
    {
      id: "evt-1",
      issueId: "issue-101",
      issueNumber: 1234,
      issueTitle: "Fix memory leak in WebSocket handler",
      repoName: "acme/backend-api",
      action: "labeled",
      category: "bug",
      priority: "P1",
      confidence: 96.5,
      draftResponse:
        "Thank you for reporting this issue. I've identified this as a memory leak in the WebSocket connection handler. The issue appears to be in the cleanup phase where connections are not properly closed. I'll label this as a P1 bug for immediate attention.",
      duplicates: [],
      labels: [
        { name: "bug", confidence: 96.5, color: "#ef4444" },
        { name: "priority:high", confidence: 92.0, color: "#f97316" },
      ],
      status: "pending",
      createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    {
      id: "evt-2",
      issueId: "issue-102",
      issueNumber: 1235,
      issueTitle: "Add dark mode support to settings page",
      repoName: "acme/frontend",
      action: "responded",
      category: "feature",
      priority: "P2",
      confidence: 89.3,
      draftResponse:
        "Great feature request! Dark mode for the settings page makes sense as we already support it elsewhere. This would involve updating the theme provider and adding dark variants to the settings components.",
      duplicates: [
        {
          issueNumber: 890,
          issueTitle: "Dark mode toggle not working on preferences",
          similarity: 0.72,
          htmlUrl: "https://github.com/acme/frontend/issues/890",
        },
      ],
      labels: [
        { name: "feature", confidence: 89.3, color: "#3b82f6" },
        { name: "ui/ux", confidence: 78.1, color: "#8b5cf6" },
      ],
      status: "pending",
      createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
    {
      id: "evt-3",
      issueId: "issue-103",
      issueNumber: 1236,
      issueTitle: "Update API documentation for v2 endpoints",
      repoName: "acme/docs",
      action: "labeled",
      category: "docs",
      priority: "P3",
      confidence: 97.1,
      draftResponse:
        "This documentation update request has been noted. The v2 API endpoints need updated examples and response schemas. Labeling as documentation task.",
      duplicates: [],
      labels: [
        { name: "documentation", confidence: 97.1, color: "#22c55e" },
      ],
      status: "approved",
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "evt-4",
      issueId: "issue-104",
      issueNumber: 1237,
      issueTitle: "Query performance degradation on large datasets",
      repoName: "acme/backend-api",
      action: "labeled",
      category: "performance",
      priority: "P1",
      confidence: 91.8,
      draftResponse:
        "This performance issue has been identified. The query planner seems to fall back to sequential scans when the dataset exceeds 1M rows. We should look into adding composite indexes and potentially implementing cursor-based pagination.",
      duplicates: [],
      labels: [
        { name: "performance", confidence: 91.8, color: "#f59e0b" },
        { name: "priority:high", confidence: 88.5, color: "#f97316" },
      ],
      status: "pending",
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "evt-5",
      issueId: "issue-105",
      issueNumber: 1238,
      issueTitle: "How to configure custom authentication?",
      repoName: "acme/sdk",
      action: "responded",
      category: "question",
      priority: "P3",
      confidence: 93.7,
      draftResponse:
        "You can configure custom authentication by implementing the `AuthProvider` interface. Here's an example:\n\n```typescript\nconst auth = new CustomAuth({ strategy: 'oauth2' });\n```\n\nSee our auth guide for more details.",
      duplicates: [],
      labels: [
        { name: "question", confidence: 93.7, color: "#eab308" },
      ],
      status: "approved",
      createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    },
  ],
};

// ─── Mock Repos ─────────────────────────────────────────────────────────────

export const mockRepos: Repo[] = [
  {
    id: "repo-1",
    name: "backend-api",
    fullName: "acme/backend-api",
    description: "Core REST API service built with Node.js and PostgreSQL",
    language: "TypeScript",
    stars: 4520,
    forks: 890,
    healthScore: 87,
    healthBreakdown: {
      documentation: 82,
      responsiveness: 91,
      issueResolution: 88,
      communityEngagement: 85,
      codeQuality: 90,
      releaseFrequency: 86,
    },
    issuesThisWeek: 23,
    lastSynced: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    avatarUrl: "https://avatars.githubusercontent.com/u/1?v=4",
    installationId: "inst-1",
  },
  {
    id: "repo-2",
    name: "frontend",
    fullName: "acme/frontend",
    description: "React-based frontend application with Next.js",
    language: "TypeScript",
    stars: 3210,
    forks: 560,
    healthScore: 92,
    healthBreakdown: {
      documentation: 95,
      responsiveness: 89,
      issueResolution: 93,
      communityEngagement: 91,
      codeQuality: 94,
      releaseFrequency: 90,
    },
    issuesThisWeek: 15,
    lastSynced: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    avatarUrl: "https://avatars.githubusercontent.com/u/2?v=4",
    installationId: "inst-1",
  },
  {
    id: "repo-3",
    name: "ml-pipeline",
    fullName: "acme/ml-pipeline",
    description: "Machine learning pipeline for issue classification",
    language: "Python",
    stars: 1870,
    forks: 340,
    healthScore: 74,
    healthBreakdown: {
      documentation: 68,
      responsiveness: 72,
      issueResolution: 78,
      communityEngagement: 70,
      codeQuality: 82,
      releaseFrequency: 74,
    },
    issuesThisWeek: 8,
    lastSynced: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    avatarUrl: "https://avatars.githubusercontent.com/u/3?v=4",
    installationId: "inst-2",
  },
  {
    id: "repo-4",
    name: "sdk",
    fullName: "acme/sdk",
    description: "Official SDK for integrating with the Acme platform",
    language: "TypeScript",
    stars: 2640,
    forks: 420,
    healthScore: 95,
    healthBreakdown: {
      documentation: 98,
      responsiveness: 94,
      issueResolution: 96,
      communityEngagement: 93,
      codeQuality: 95,
      releaseFrequency: 94,
    },
    issuesThisWeek: 5,
    lastSynced: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    avatarUrl: "https://avatars.githubusercontent.com/u/4?v=4",
    installationId: "inst-1",
  },
  {
    id: "repo-5",
    name: "docs",
    fullName: "acme/docs",
    description: "Documentation site built with Docusaurus",
    language: "MDX",
    stars: 890,
    forks: 210,
    healthScore: 58,
    healthBreakdown: {
      documentation: 45,
      responsiveness: 62,
      issueResolution: 55,
      communityEngagement: 68,
      codeQuality: 70,
      releaseFrequency: 48,
    },
    issuesThisWeek: 12,
    lastSynced: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    avatarUrl: "https://avatars.githubusercontent.com/u/5?v=4",
    installationId: "inst-1",
  },
  {
    id: "repo-6",
    name: "infra",
    fullName: "acme/infra",
    description: "Infrastructure as Code with Terraform and Kubernetes",
    language: "HCL",
    stars: 760,
    forks: 150,
    healthScore: 81,
    healthBreakdown: {
      documentation: 78,
      responsiveness: 85,
      issueResolution: 80,
      communityEngagement: 76,
      codeQuality: 88,
      releaseFrequency: 79,
    },
    issuesThisWeek: 3,
    lastSynced: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    avatarUrl: "https://avatars.githubusercontent.com/u/6?v=4",
    installationId: "inst-2",
  },
];

// ─── Mock Issues ────────────────────────────────────────────────────────────

export const mockIssues: Issue[] = [
  {
    id: "issue-101",
    number: 1234,
    title: "Fix memory leak in WebSocket handler",
    body: "When multiple clients connect and disconnect rapidly, memory usage grows unboundedly.",
    state: "triaged",
    category: "bug",
    priority: "P1",
    complexity: "hard",
    labels: ["bug", "priority:high", "websocket"],
    author: { login: "jsmith", avatarUrl: "https://avatars.githubusercontent.com/u/10?v=4", htmlUrl: "https://github.com/jsmith" },
    assignees: [],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    repoId: "repo-1",
    repoName: "acme/backend-api",
    htmlUrl: "https://github.com/acme/backend-api/issues/1234",
    confidence: 96.5,
    estimatedMinutes: 240,
    prerequisites: ["Node.js", "WebSocket", "Memory profiling"],
  },
  {
    id: "issue-102",
    number: 1235,
    title: "Add dark mode support to settings page",
    body: "The settings page doesn't respect the user's dark mode preference.",
    state: "triaged",
    category: "feature",
    priority: "P2",
    complexity: "medium",
    labels: ["feature", "ui/ux"],
    author: { login: "alee", avatarUrl: "https://avatars.githubusercontent.com/u/11?v=4", htmlUrl: "https://github.com/alee" },
    assignees: [],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    repoId: "repo-2",
    repoName: "acme/frontend",
    htmlUrl: "https://github.com/acme/frontend/issues/1235",
    confidence: 89.3,
    estimatedMinutes: 120,
    prerequisites: ["React", "CSS", "Tailwind"],
  },
  {
    id: "issue-103",
    number: 1236,
    title: "Update API documentation for v2 endpoints",
    body: "The v2 API has been released but documentation still references v1 schemas.",
    state: "open",
    category: "docs",
    priority: "P3",
    complexity: "easy",
    labels: ["documentation"],
    author: { login: "mwong", avatarUrl: "https://avatars.githubusercontent.com/u/12?v=4", htmlUrl: "https://github.com/mwong" },
    assignees: [],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    repoId: "repo-5",
    repoName: "acme/docs",
    htmlUrl: "https://github.com/acme/docs/issues/1236",
    confidence: 97.1,
    estimatedMinutes: 60,
    prerequisites: ["Technical Writing", "REST APIs"],
  },
  {
    id: "issue-104",
    number: 1237,
    title: "Query performance degradation on large datasets",
    body: "Queries slow down significantly when tables exceed 1M rows.",
    state: "triaged",
    category: "performance",
    priority: "P1",
    complexity: "expert",
    labels: ["performance", "priority:high", "database"],
    author: { login: "dchen", avatarUrl: "https://avatars.githubusercontent.com/u/13?v=4", htmlUrl: "https://github.com/dchen" },
    assignees: [],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    repoId: "repo-1",
    repoName: "acme/backend-api",
    htmlUrl: "https://github.com/acme/backend-api/issues/1237",
    confidence: 91.8,
    estimatedMinutes: 480,
    prerequisites: ["PostgreSQL", "Query optimization", "Indexing"],
  },
  {
    id: "issue-105",
    number: 1238,
    title: "How to configure custom authentication?",
    body: "I need to implement custom OAuth2 flow but can't find documentation.",
    state: "triaged",
    category: "question",
    priority: "P3",
    complexity: "trivial",
    labels: ["question"],
    author: { login: "kpatel", avatarUrl: "https://avatars.githubusercontent.com/u/14?v=4", htmlUrl: "https://github.com/kpatel" },
    assignees: [],
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    repoId: "repo-4",
    repoName: "acme/sdk",
    htmlUrl: "https://github.com/acme/sdk/issues/1238",
    confidence: 93.7,
    estimatedMinutes: 15,
    prerequisites: ["OAuth2"],
  },
];

// ─── Mock Recommendations ───────────────────────────────────────────────────

export const mockRecommendations: Recommendation[] = [
  {
    id: "rec-1",
    issue: mockIssues[2],
    matchScore: 95,
    healthLevel: 4,
    difficulty: 2,
    estimatedMinutes: 60,
    prerequisites: ["Technical Writing", "REST APIs"],
    maintainerResponseTime: "< 2 hours",
    repoAvatarUrl: "https://avatars.githubusercontent.com/u/5?v=4",
  },
  {
    id: "rec-2",
    issue: mockIssues[1],
    matchScore: 88,
    healthLevel: 5,
    difficulty: 3,
    estimatedMinutes: 120,
    prerequisites: ["React", "CSS", "Tailwind"],
    maintainerResponseTime: "< 4 hours",
    repoAvatarUrl: "https://avatars.githubusercontent.com/u/2?v=4",
  },
  {
    id: "rec-3",
    issue: mockIssues[0],
    matchScore: 72,
    healthLevel: 4,
    difficulty: 4,
    estimatedMinutes: 240,
    prerequisites: ["Node.js", "WebSocket", "Memory profiling"],
    maintainerResponseTime: "< 6 hours",
    repoAvatarUrl: "https://avatars.githubusercontent.com/u/1?v=4",
  },
  {
    id: "rec-4",
    issue: {
      ...mockIssues[4],
      title: "Add TypeScript generics support to SDK client",
      category: "feature",
      complexity: "medium",
      priority: "P2",
    },
    matchScore: 83,
    healthLevel: 5,
    difficulty: 3,
    estimatedMinutes: 180,
    prerequisites: ["TypeScript", "Generics", "SDK Design"],
    maintainerResponseTime: "< 1 hour",
    repoAvatarUrl: "https://avatars.githubusercontent.com/u/4?v=4",
  },
  {
    id: "rec-5",
    issue: {
      ...mockIssues[3],
      title: "Implement connection pooling for database queries",
      category: "performance",
      complexity: "hard",
      priority: "P1",
    },
    matchScore: 67,
    healthLevel: 4,
    difficulty: 4,
    estimatedMinutes: 360,
    prerequisites: ["PostgreSQL", "Connection pooling", "Node.js"],
    maintainerResponseTime: "< 8 hours",
    repoAvatarUrl: "https://avatars.githubusercontent.com/u/1?v=4",
  },
];

// ─── Mock Skill Profile ─────────────────────────────────────────────────────

export const mockSkillProfile: SkillProfile = {
  username: "contributor-dev",
  avatarUrl: "https://avatars.githubusercontent.com/u/100?v=4",
  bio: "Full-stack developer passionate about open source and developer tools.",
  skills: [
    {
      name: "Backend",
      skills: [
        { name: "Node.js", proficiency: 88, endorsements: 12 },
        { name: "PostgreSQL", proficiency: 75, endorsements: 8 },
        { name: "Redis", proficiency: 62, endorsements: 5 },
        { name: "GraphQL", proficiency: 70, endorsements: 6 },
      ],
    },
    {
      name: "Frontend",
      skills: [
        { name: "React", proficiency: 92, endorsements: 15 },
        { name: "TypeScript", proficiency: 85, endorsements: 14 },
        { name: "Next.js", proficiency: 78, endorsements: 9 },
        { name: "CSS/Tailwind", proficiency: 80, endorsements: 7 },
      ],
    },
    {
      name: "DevOps",
      skills: [
        { name: "Docker", proficiency: 65, endorsements: 4 },
        { name: "Kubernetes", proficiency: 45, endorsements: 2 },
        { name: "CI/CD", proficiency: 72, endorsements: 6 },
      ],
    },
    {
      name: "Data",
      skills: [
        { name: "Python", proficiency: 70, endorsements: 8 },
        { name: "SQL", proficiency: 82, endorsements: 10 },
        { name: "Data Modeling", proficiency: 60, endorsements: 3 },
      ],
    },
  ],
  languages: [
    { language: "TypeScript", proficiency: 90, linesWritten: 245000, color: "#3178c6" },
    { language: "Python", proficiency: 72, linesWritten: 89000, color: "#3572A5" },
    { language: "JavaScript", proficiency: 88, linesWritten: 178000, color: "#f1e05a" },
    { language: "Go", proficiency: 45, linesWritten: 23000, color: "#00ADD8" },
    { language: "Rust", proficiency: 30, linesWritten: 8500, color: "#dea584" },
    { language: "SQL", proficiency: 78, linesWritten: 52000, color: "#e38c00" },
  ],
  contributions: [
    { id: "c-1", repoName: "vercel/next.js", issueTitle: "Fix hydration mismatch in app router", difficulty: "hard", completedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), htmlUrl: "#" },
    { id: "c-2", repoName: "prisma/prisma", issueTitle: "Add connection pool timeout config", difficulty: "medium", completedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(), htmlUrl: "#" },
    { id: "c-3", repoName: "tailwindlabs/tailwindcss", issueTitle: "Update dark mode docs", difficulty: "easy", completedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(), htmlUrl: "#" },
    { id: "c-4", repoName: "facebook/react", issueTitle: "Fix useEffect cleanup race condition", difficulty: "expert", completedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), htmlUrl: "#" },
    { id: "c-5", repoName: "microsoft/typescript", issueTitle: "Improve type narrowing for discriminated unions", difficulty: "hard", completedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(), htmlUrl: "#" },
    { id: "c-6", repoName: "denoland/deno", issueTitle: "Add HTTP/2 support docs", difficulty: "easy", completedAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(), htmlUrl: "#" },
  ],
  domains: ["Web Development", "Developer Tools", "Databases", "API Design"],
  isPublic: true,
  totalContributions: 47,
  currentStreak: 12,
  longestStreak: 34,
};

// ─── Mock Triage Config ─────────────────────────────────────────────────────

export const mockTriageConfig: TriageConfig = {
  labelMapping: {
    bug: "bug",
    feature: "enhancement",
    question: "question",
    docs: "documentation",
    chore: "maintenance",
    security: "security",
    performance: "performance",
  },
  responseTone: "friendly",
  autoApproveThreshold: 95,
  enableDuplicateDetection: true,
  enableAutoLabeling: true,
  enableAutoResponse: true,
};
